In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"../data/raw/big_startup_success_dataset.csv")

In [ ]:
# Convert Date Columns
date_columns = [
    "founded_at",
    "first_funding_at",
    "last_funding_at"
]

for column in date_columns:
    df[column] = pd.to_datetime(df[column],errors="coerce")

In [4]:
# Extract Year Columns
df["founded_year"] = df["founded_at"].dt.year
df["first_funding_year"] = df["first_funding_at"].dt.year
df["last_funding_year"] = df["last_funding_at"].dt.year

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66368 entries, 0 to 66367
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   permalink           66368 non-null  object
 1   name                66367 non-null  object
 2   homepage_url        61310 non-null  object
 3   category_list       63220 non-null  object
 4   funding_total_usd   66368 non-null  object
 5   status              66368 non-null  object
 6   country_code        59410 non-null  object
 7   state_code          57821 non-null  object
 8   region              58338 non-null  object
 9   city                58340 non-null  object
 10  funding_rounds      66368 non-null  int64
 11  founded_at          51143 non-null  datetime64[ns]
 12  first_funding_at    66341 non-null  datetime64[ns]
 13  last_funding_at     66368 non-null  datetime64[ns]
 14  founded_year        51143 non-null  float64
 15  first_funding_year  66341 non-null  float64
 16  last_funding_year   66368 non-null  int32
dtypes: datetime64[ns](3), float64(2), int32(1), int64(1), object(10)
memory usage: 8.4+ MB

In [30]:
df.isnull().sum().sort_values(ascending=False)

founded_year          15225
founded_at            15225
state_code             8547
region                 8030
city                   8028
country_code           6958
homepage_url           5058
category_list          3148
first_funding_at         27
first_funding_year       27
name                      1
last_funding_at           0
permalink                 0
funding_rounds            0
status                    0
funding_total_usd         0
last_funding_year         0
dtype: int64

In [7]:
# Missing Percentage
missing_percentage = (df.isnull().mean()*100).sort_values(ascending=False)

missing_percentage

founded_year          22.940272
founded_at            22.940272
state_code            12.878194
region                12.099204
city                  12.096191
country_code          10.483968
homepage_url           7.621143
category_list          4.743250
first_funding_at       0.040682
first_funding_year     0.040682
name                   0.001507
last_funding_at        0.000000
permalink              0.000000
funding_rounds         0.000000
status                 0.000000
funding_total_usd      0.000000
last_funding_year      0.000000
dtype: float64

In [8]:
# Duplicate Row Analysis
duplicate_rows = df.duplicated().sum()
print("Total Duplicate Rows :", duplicate_rows)

Total Duplicate Rows : 0

In [9]:
#  Unique Value Analysis
df.nunique().sort_values()

status                    4
funding_rounds           19
first_funding_year       40
last_funding_year        41
country_code            137
founded_year            176
state_code              311
region                 1092
founded_at             3974
last_funding_at        4518
first_funding_at       4814
city                   5111
funding_total_usd     18896
category_list         27296
homepage_url          61191
name                  66102
permalink             66368
dtype: int64

In [10]:
# Complete Dataset Overview
df.describe(include="all")

,permalink,name,homepage_url,category_list,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,first_funding_at,last_funding_at,founded_year,first_funding_year,last_funding_year
count,66368,66367,61310,63220,66368,66368,59410,57821,58338,58340,66368.000000,51143,66341,66368,51143.000000,66341.000000,66368.000000
unique,66368,66102,61191,27296,18896,4,137,311,1092,5111,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,/organization/-fame,Blink,http://www.askforoffer.com,Software,-,operating,USA,CA,SF Bay Area,San Francisco,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,4,5,3995,12785,53034,37601,12900,8804,3526,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.732522,2007-12-25 07:34:57.014254080,2011-07-20 08:19:11.722162688,2012-06-26 21:44:09.228544,2007.762294,2011.083990,2012.010125
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1749-01-01 00:00:00,1960-01-01 00:00:00,1971-01-01 00:00:00,1749.000000,1960.000000,1971.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,2006-01-01 00:00:00,2009-10-23 00:00:00,2011-02-01 00:00:00,2006.000000,2009.000000,2011.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,2010-09-01 00:00:00,2012-08-01 00:00:00,2013-09-01 00:00:00,2010.000000,2012.000000,2013.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,2013-01-01 00:00:00,2014-04-02 00:00:00,2014-11-17 00:00:00,2013.000000,2014.000000,2014.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.000000,2105-02-17 00:00:00,2015-12-05 00:00:00,2115-12-01 00:00:00,2105.000000,2015.000000,2115.000000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.360251,NaN,NaN,NaN,10.302143,3.638379,3.406581

In [28]:
df.head(20)
# df.tail(20)

,permalink,name,homepage_url,category_list,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,first_funding_at,last_funding_at,founded_year,first_funding_year,last_funding_year
0,/organization/-fame,#fame,http://livfame.com,Media,10000000,operating,IND,16,Mumbai,Mumbai,1,NaT,2015-01-05,2015-01-05,NaN,2015.0,2015
1,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,700000,operating,USA,DE,DE - Other,Delaware City,2,2014-09-04,2014-03-01,2014-10-14,2014.0,2014.0,2014
2,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,3406878,operating,NaN,NaN,NaN,NaN,1,NaT,2014-01-30,2014-01-30,NaN,2014.0,2014
3,/organization/0-6-com,0-6.com,http://www.0-6.com,Curated Web,2000000,operating,CHN,22,Beijing,Beijing,1,2007-01-01,2008-03-19,2008-03-19,2007.0,2008.0,2008
4,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,-,operating,USA,IL,"Springfield, Illinois",Champaign,1,2010-01-01,2014-07-24,2014-07-24,2010.0,2014.0,2014
5,/organization/01games-technology,01Games Technology,http://www.01games.hk/,Games,41250,operating,HKG,NaN,Hong Kong,Hong Kong,1,NaT,2014-07-01,2014-07-01,NaN,2014.0,2014
6,/organization/0ndine-biomedical-inc,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,762851,operating,CAN,BC,Vancouver,Vancouver,2,1997-01-01,2009-09-11,2009-12-21,1997.0,2009.0,2009
7,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,33600000,operating,USA,CA,SF Bay Area,Mountain View,4,2011-01-01,2013-01-03,2015-11-09,2011.0,2013.0,2015
8,/organization/1,One Inc.,http://whatis1.com,Mobile,1150050,operating,USA,CA,SF Bay Area,San Francisco,3,2011-08-01,2011-07-20,2014-02-05,2011.0,2011.0,2014
9,/organization/1-2-3-listo,"1,2,3 Listo",http://www.123listo.com,E-Commerce,40000,operating,CHL,12,Santiago,Las Condes,1,2012-01-01,2013-02-18,2013-02-18,2012.0,2013.0,2013
10,/organization/1-4-all,1-4 All,NaN,Entertainment|Games|Software,-,operating,USA,NC,NC - Other,Connellys Springs,1,NaT,2013-04-21,2013-04-21,NaN,2013.0,2013
11,/organization/1-618-technology,1.618 Technology,http://www.Homeandcondogallery.com,Networking|Real Estate|Web Hosting,-,operating,USA,FL,Orlando,Orlando,1,2013-12-07,2014-01-22,2014-01-22,2013.0,2014.0,2014
12,/organization/1-800-dentist,1-800-DENTIST,http://www.1800dentist.com,Health and Wellness,-,operating,USA,CA,Los Angeles,Los Angeles,1,1986-01-01,2010-08-19,2010-08-19,1986.0,2010.0,2010
13,/organization/1-800-doctors,1-800-DOCTORS,http://1800doctors.com,Health and Wellness,1750000,operating,USA,NJ,Newark,Iselin,1,1984-01-01,2011-03-02,2011-03-02,1984.0,2011.0,2011
14,/organization/1-800-publicrelations-inc-,"1-800-PublicRelations, Inc.",http://www.1800publicrelations.com,Internet Marketing|Media|Public Relations,6000000,operating,USA,NY,New York City,New York,1,2013-10-24,2015-02-01,2015-02-01,2013.0,2015.0,2015
15,/organization/1-mainstream,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,5000000,acquired,USA,CA,SF Bay Area,Cupertino,1,2012-03-01,2015-03-17,2015-03-17,2012.0,2015.0,2015
16,/organization/1-of-99,1 of 99,NaN,Entertainment|Games,100000,operating,USA,CA,SF Bay Area,Mountain View,1,2014-12-01,2014-12-13,2014-12-13,2014.0,2014.0,2014
17,/organization/10-20-media,10-20 Media,http://www.10-20media.com,E-Commerce,2050000,operating,USA,MD,Baltimore,Woodbine,4,2001-01-01,2009-06-18,2011-12-28,2001.0,2009.0,2011
18,/organization/10-minutes-with,10 Minutes With,http://10minuteswith.com,Education,4400000,operating,GBR,H9,London,London,2,2013-01-01,2013-01-01,2014-10-09,2013.0,2013.0,2014
19,/organization/1000-corks,1000 Corks,http://1000corks.com,Search,40000,operating,USA,OR,"Portland, Oregon",Lake Oswego,1,2008-01-01,2011-08-23,2011-08-23,2008.0,2011.0,2011

In [17]:
df[df['funding_total_usd'] == '-'].shape

(12785, 17)

In [18]:
df["funding_total_usd"].value_counts().head(10)

funding_total_usd
-           12785
1000000      1147
100000        983
500000        979
2000000       820
50000         767
40000         696
250000        645
10000000      633
1500000       619
Name: count, dtype: int64

In [19]:
df["funding_total_usd"].dtype

dtype('O')

In [21]:
df["funding_total_usd"].str.contains(r"\$", na=False).sum()

np.int64(0)

# Day-03: Initial Data Exploration & Data Quality Assessment

## Objective

The goal of Day-03 was to understand the structure and quality of the startup dataset before starting the preprocessing phase.

---

##  Tasks Completed

### 1. Imported Required Libraries
- NumPy
- Pandas

### 2. Loaded the Dataset
- Successfully loaded the Startup Success Dataset.

### 3. Converted Date Columns
Converted the following columns into datetime format:
- founded_at
- first_funding_at
- last_funding_at

Invalid date values were converted into `NaT`.

### 4. Feature Engineering
Extracted year information from datetime columns:
- founded_year
- first_funding_year
- last_funding_year

### 5. Dataset Structure Analysis
Performed dataset inspection using:
- `df.info()`

Checked:
- Total rows
- Total columns
- Data types
- Non-null values
- Memory usage

### 6. Missing Value Analysis
Calculated:
- Missing value count
- Missing value percentage

### 7. Duplicate Analysis
Checked duplicate rows in the dataset.

### 8. Unique Value Analysis
Calculated unique values for every feature.

### 9. Statistical Summary
Generated descriptive statistics using:

- Numerical Features
- Categorical Features

### 10. Dataset Preview
Inspected sample records using:
- `head()`

### 11. Funding Column Investigation
Performed an initial investigation on `funding_total_usd`.

Checked:
- Missing placeholders (`-`)
- Currency symbols (`$`)
- Datatype
- Most frequent values

---

# Key Findings

- Date columns required datetime conversion.
- New year-based features were successfully created.
- Several columns contain missing values.
- Dataset contains categorical and numerical features.
- `funding_total_usd` requires cleaning before analysis.
- Dataset quality assessment completed successfully.

---

# Outcome

The dataset has been successfully explored and understood.

No preprocessing has been performed yet.

The notebook is now ready for the data cleaning phase.

---

# Next Step (Day-04)

- Clean `funding_total_usd`
- Handle missing values
- Detect outliers
- Perform feature-wise preprocessing
- Start Univariate Analysis